name: photo_sync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.7.1
  network_info_plus: ^6.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  lzma: ^1.0.1
  device_info_plus: ^9.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
