name: photo_sync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.7.1
  network_info_plus: ^6.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  lzma: ^1.0.1
  url_launcher: ^6.3.2
  wakelock_plus: ^1.4.0
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
